/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'clothing' : null } |
  { 'other' : null } |
  { 'home' : null } |
  { 'books' : null } |
  { 'sports' : null } |
  { 'digital' : null } |
  { 'services' : null } |
  { 'electronics' : null };
export interface Listing {
  'id' : ListingId,
  'coverImageUrl' : string,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'category' : Category,
  'sellerId' : UserId,
  'priceUsd' : number,
}
export interface ListingFilter {
  'minPriceUsd' : [] | [number],
  'maxPriceUsd' : [] | [number],
  'category' : [] | [Category],
  'searchQuery' : [] | [string],
}
export type ListingId = bigint;
export interface ListingInput {
  'coverImageUrl' : string,
  'title' : string,
  'description' : string,
  'category' : Category,
  'priceUsd' : number,
}
export interface PaymentInitResult {
  'expiresAt' : Timestamp,
  'paymentAddress' : string,
  'currency' : string,
  'paymentId' : string,
  'paymentAmount' : number,
  'transactionId' : TransactionId,
}
export interface PayoutResult {
  'stripeTransferId' : string,
  'amountUsd' : number,
  'transactionId' : TransactionId,
}
export interface SellerBalance {
  'availableUsd' : number,
  'pendingUsd' : number,
}
export type Timestamp = bigint;
export interface Transaction {
  'id' : TransactionId,
  'status' : TransactionStatus,
  'cryptoAddress' : [] | [string],
  'nowPaymentsPaymentId' : [] | [string],
  'listingId' : ListingId,
  'createdAt' : Timestamp,
  'stripeTransferId' : [] | [string],
  'updatedAt' : Timestamp,
  'platformFeeUsd' : number,
  'buyerId' : UserId,
  'amountUsd' : number,
  'sellerId' : UserId,
  'sellerAmountUsd' : number,
  'cryptoTxnHash' : [] | [string],
  'cryptoCurrency' : [] | [string],
}
export type TransactionId = bigint;
export type TransactionStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'displayPictureUrl' : string,
  'stripeConnectAccountId' : [] | [string],
}
export type UserRole = { 'both' : null } |
  { 'seller' : null } |
  { 'buyer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'browseListings' : ActorMethod<[[] | [ListingFilter]], Array<Listing>>,
  'connectStripeAccount' : ActorMethod<[string], undefined>,
  'createListing' : ActorMethod<[ListingInput], Listing>,
  'deleteListing' : ActorMethod<[ListingId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getListing' : ActorMethod<[ListingId], [] | [Listing]>,
  'getMyListings' : ActorMethod<[], Array<Listing>>,
  'getMyTransactionsAsBuyer' : ActorMethod<[], Array<Transaction>>,
  'getMyTransactionsAsSeller' : ActorMethod<[], Array<Transaction>>,
  'getSellerBalance' : ActorMethod<[], SellerBalance>,
  'getTransaction' : ActorMethod<[TransactionId], [] | [Transaction]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'initiateCryptoPayment' : ActorMethod<[ListingId, string], PaymentInitResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPaymentConfigured' : ActorMethod<[], boolean>,
  'requestPayout' : ActorMethod<[TransactionId], PayoutResult>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string, UserRole],
    UserProfile
  >,
  'setNowPaymentsApiKey' : ActorMethod<[string], undefined>,
  'setStripeSecretKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateListing' : ActorMethod<[ListingId, ListingInput], [] | [Listing]>,
  'updatePaymentStatus' : ActorMethod<[string], [] | [Transaction]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];