/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'clothing' : IDL.Null,
  'other' : IDL.Null,
  'home' : IDL.Null,
  'books' : IDL.Null,
  'sports' : IDL.Null,
  'digital' : IDL.Null,
  'services' : IDL.Null,
  'electronics' : IDL.Null,
});
export const ListingFilter = IDL.Record({
  'minPriceUsd' : IDL.Opt(IDL.Float64),
  'maxPriceUsd' : IDL.Opt(IDL.Float64),
  'category' : IDL.Opt(Category),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const ListingId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Listing = IDL.Record({
  'id' : ListingId,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'category' : Category,
  'sellerId' : UserId,
  'priceUsd' : IDL.Float64,
});
export const ListingInput = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'priceUsd' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'both' : IDL.Null,
  'seller' : IDL.Null,
  'buyer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'displayPictureUrl' : IDL.Text,
  'stripeConnectAccountId' : IDL.Opt(IDL.Text),
});
export const TransactionId = IDL.Nat;
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'cryptoAddress' : IDL.Opt(IDL.Text),
  'nowPaymentsPaymentId' : IDL.Opt(IDL.Text),
  'listingId' : ListingId,
  'createdAt' : Timestamp,
  'stripeTransferId' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'platformFeeUsd' : IDL.Float64,
  'buyerId' : UserId,
  'amountUsd' : IDL.Float64,
  'sellerId' : UserId,
  'sellerAmountUsd' : IDL.Float64,
  'cryptoTxnHash' : IDL.Opt(IDL.Text),
  'cryptoCurrency' : IDL.Opt(IDL.Text),
});
export const SellerBalance = IDL.Record({
  'availableUsd' : IDL.Float64,
  'pendingUsd' : IDL.Float64,
});
export const PaymentInitResult = IDL.Record({
  'expiresAt' : Timestamp,
  'paymentAddress' : IDL.Text,
  'currency' : IDL.Text,
  'paymentId' : IDL.Text,
  'paymentAmount' : IDL.Float64,
  'transactionId' : TransactionId,
});
export const PayoutResult = IDL.Record({
  'stripeTransferId' : IDL.Text,
  'amountUsd' : IDL.Float64,
  'transactionId' : TransactionId,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'browseListings' : IDL.Func(
      [IDL.Opt(ListingFilter)],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'connectStripeAccount' : IDL.Func([IDL.Text], [], []),
  'createListing' : IDL.Func([ListingInput], [Listing], []),
  'deleteListing' : IDL.Func([ListingId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getMyTransactionsAsBuyer' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMyTransactionsAsSeller' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getSellerBalance' : IDL.Func([], [SellerBalance], ['query']),
  'getTransaction' : IDL.Func(
      [TransactionId],
      [IDL.Opt(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'initiateCryptoPayment' : IDL.Func(
      [ListingId, IDL.Text],
      [PaymentInitResult],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPaymentConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'requestPayout' : IDL.Func([TransactionId], [PayoutResult], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [UserProfile],
      [],
    ),
  'setNowPaymentsApiKey' : IDL.Func([IDL.Text], [], []),
  'setStripeSecretKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateListing' : IDL.Func([ListingId, ListingInput], [IDL.Opt(Listing)], []),
  'updatePaymentStatus' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'clothing' : IDL.Null,
    'other' : IDL.Null,
    'home' : IDL.Null,
    'books' : IDL.Null,
    'sports' : IDL.Null,
    'digital' : IDL.Null,
    'services' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const ListingFilter = IDL.Record({
    'minPriceUsd' : IDL.Opt(IDL.Float64),
    'maxPriceUsd' : IDL.Opt(IDL.Float64),
    'category' : IDL.Opt(Category),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const ListingId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Listing = IDL.Record({
    'id' : ListingId,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'category' : Category,
    'sellerId' : UserId,
    'priceUsd' : IDL.Float64,
  });
  const ListingInput = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'priceUsd' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'both' : IDL.Null,
    'seller' : IDL.Null,
    'buyer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'displayPictureUrl' : IDL.Text,
    'stripeConnectAccountId' : IDL.Opt(IDL.Text),
  });
  const TransactionId = IDL.Nat;
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'cryptoAddress' : IDL.Opt(IDL.Text),
    'nowPaymentsPaymentId' : IDL.Opt(IDL.Text),
    'listingId' : ListingId,
    'createdAt' : Timestamp,
    'stripeTransferId' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'platformFeeUsd' : IDL.Float64,
    'buyerId' : UserId,
    'amountUsd' : IDL.Float64,
    'sellerId' : UserId,
    'sellerAmountUsd' : IDL.Float64,
    'cryptoTxnHash' : IDL.Opt(IDL.Text),
    'cryptoCurrency' : IDL.Opt(IDL.Text),
  });
  const SellerBalance = IDL.Record({
    'availableUsd' : IDL.Float64,
    'pendingUsd' : IDL.Float64,
  });
  const PaymentInitResult = IDL.Record({
    'expiresAt' : Timestamp,
    'paymentAddress' : IDL.Text,
    'currency' : IDL.Text,
    'paymentId' : IDL.Text,
    'paymentAmount' : IDL.Float64,
    'transactionId' : TransactionId,
  });
  const PayoutResult = IDL.Record({
    'stripeTransferId' : IDL.Text,
    'amountUsd' : IDL.Float64,
    'transactionId' : TransactionId,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'browseListings' : IDL.Func(
        [IDL.Opt(ListingFilter)],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'connectStripeAccount' : IDL.Func([IDL.Text], [], []),
    'createListing' : IDL.Func([ListingInput], [Listing], []),
    'deleteListing' : IDL.Func([ListingId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getMyTransactionsAsBuyer' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getMyTransactionsAsSeller' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getSellerBalance' : IDL.Func([], [SellerBalance], ['query']),
    'getTransaction' : IDL.Func(
        [TransactionId],
        [IDL.Opt(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'initiateCryptoPayment' : IDL.Func(
        [ListingId, IDL.Text],
        [PaymentInitResult],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPaymentConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'requestPayout' : IDL.Func([TransactionId], [PayoutResult], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [UserProfile],
        [],
      ),
    'setNowPaymentsApiKey' : IDL.Func([IDL.Text], [], []),
    'setStripeSecretKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateListing' : IDL.Func(
        [ListingId, ListingInput],
        [IDL.Opt(Listing)],
        [],
      ),
    'updatePaymentStatus' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], []),
  });
};

export const init = ({ IDL }) => { return []; };