/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Listing {
    id: ListingId;
    coverImageUrl: string;
    title: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: Timestamp;
    category: Category;
    sellerId: UserId;
    priceUsd: number;
}
export interface SellerBalance {
    availableUsd: number;
    pendingUsd: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Transaction {
    id: TransactionId;
    status: TransactionStatus;
    cryptoAddress?: string;
    nowPaymentsPaymentId?: string;
    listingId: ListingId;
    createdAt: Timestamp;
    stripeTransferId?: string;
    updatedAt: Timestamp;
    platformFeeUsd: number;
    buyerId: UserId;
    amountUsd: number;
    sellerId: UserId;
    sellerAmountUsd: number;
    cryptoTxnHash?: string;
    cryptoCurrency?: string;
}
export type UserId = Principal;
export type TransactionId = bigint;
export interface ListingInput {
    coverImageUrl: string;
    title: string;
    description: string;
    category: Category;
    priceUsd: number;
}
export interface PayoutResult {
    stripeTransferId: string;
    amountUsd: number;
    transactionId: TransactionId;
}
export interface PaymentInitResult {
    expiresAt: Timestamp;
    paymentAddress: string;
    currency: string;
    paymentId: string;
    paymentAmount: number;
    transactionId: TransactionId;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type ListingId = bigint;
export interface ListingFilter {
    minPriceUsd?: number;
    maxPriceUsd?: number;
    category?: Category;
    searchQuery?: string;
}
export interface UserProfile {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    displayPictureUrl: string;
    stripeConnectAccountId?: string;
}
export enum Category {
    clothing = "clothing",
    other = "other",
    home = "home",
    books = "books",
    sports = "sports",
    digital = "digital",
    services = "services",
    electronics = "electronics"
}
export enum TransactionStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum UserRole {
    both = "both",
    seller = "seller",
    buyer = "buyer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    browseListings(filter: ListingFilter | null): Promise<Array<Listing>>;
    connectStripeAccount(stripeConnectAccountId: string): Promise<void>;
    createListing(input: ListingInput): Promise<Listing>;
    deleteListing(listingId: ListingId): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getListing(listingId: ListingId): Promise<Listing | null>;
    getMyListings(): Promise<Array<Listing>>;
    getMyTransactionsAsBuyer(): Promise<Array<Transaction>>;
    getMyTransactionsAsSeller(): Promise<Array<Transaction>>;
    getSellerBalance(): Promise<SellerBalance>;
    getTransaction(txnId: TransactionId): Promise<Transaction | null>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    initiateCryptoPayment(listingId: ListingId, cryptoCurrency: string): Promise<PaymentInitResult>;
    isCallerAdmin(): Promise<boolean>;
    isPaymentConfigured(): Promise<boolean>;
    requestPayout(txnId: TransactionId): Promise<PayoutResult>;
    saveCallerUserProfile(name: string, email: string, displayPictureUrl: string, role: UserRole): Promise<UserProfile>;
    setNowPaymentsApiKey(apiKey: string): Promise<void>;
    setStripeSecretKey(secretKey: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateListing(listingId: ListingId, input: ListingInput): Promise<Listing | null>;
    updatePaymentStatus(paymentId: string): Promise<Transaction | null>;
}
import type { Category as _Category, Listing as _Listing, ListingFilter as _ListingFilter, ListingId as _ListingId, ListingInput as _ListingInput, Timestamp as _Timestamp, Transaction as _Transaction, TransactionId as _TransactionId, TransactionStatus as _TransactionStatus, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async browseListings(arg0: ListingFilter | null): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseListings(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseListings(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async connectStripeAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectStripeAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectStripeAccount(arg0);
            return result;
        }
    }
    async createListing(arg0: ListingInput): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(to_candid_ListingInput_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Listing_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(to_candid_ListingInput_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Listing_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteListing(arg0: ListingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: ListingId): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactionsAsBuyer(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactionsAsBuyer();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactionsAsBuyer();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactionsAsSeller(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactionsAsSeller();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactionsAsSeller();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSellerBalance(): Promise<SellerBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerBalance();
            return result;
        }
    }
    async getTransaction(arg0: TransactionId): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateCryptoPayment(arg0: ListingId, arg1: string): Promise<PaymentInitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateCryptoPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateCryptoPayment(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPaymentConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPaymentConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPaymentConfigured();
            return result;
        }
    }
    async requestPayout(arg0: TransactionId): Promise<PayoutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPayout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPayout(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string, arg3: UserRole): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg3));
                return from_candid_UserProfile_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg3));
            return from_candid_UserProfile_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async setNowPaymentsApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNowPaymentsApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNowPaymentsApiKey(arg0);
            return result;
        }
    }
    async setStripeSecretKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeSecretKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeSecretKey(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateListing(arg0: ListingId, arg1: ListingInput): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, to_candid_ListingInput_n13(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, to_candid_ListingInput_n13(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePaymentStatus(arg0: string): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Listing | null {
    return value.length === 0 ? null : from_candid_Listing_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ListingId;
    coverImageUrl: string;
    title: string;
    createdAt: _Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: _Timestamp;
    category: _Category;
    sellerId: _UserId;
    priceUsd: number;
}): {
    id: ListingId;
    coverImageUrl: string;
    title: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: Timestamp;
    category: Category;
    sellerId: UserId;
    priceUsd: number;
} {
    return {
        id: value.id,
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        category: from_candid_Category_n11(_uploadFile, _downloadFile, value.category),
        sellerId: value.sellerId,
        priceUsd: value.priceUsd
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
    displayPictureUrl: string;
    stripeConnectAccountId: [] | [string];
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    displayPictureUrl: string;
    stripeConnectAccountId?: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n18(_uploadFile, _downloadFile, value.role),
        email: value.email,
        displayPictureUrl: value.displayPictureUrl,
        stripeConnectAccountId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.stripeConnectAccountId))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    status: _TransactionStatus;
    cryptoAddress: [] | [string];
    nowPaymentsPaymentId: [] | [string];
    listingId: _ListingId;
    createdAt: _Timestamp;
    stripeTransferId: [] | [string];
    updatedAt: _Timestamp;
    platformFeeUsd: number;
    buyerId: _UserId;
    amountUsd: number;
    sellerId: _UserId;
    sellerAmountUsd: number;
    cryptoTxnHash: [] | [string];
    cryptoCurrency: [] | [string];
}): {
    id: TransactionId;
    status: TransactionStatus;
    cryptoAddress?: string;
    nowPaymentsPaymentId?: string;
    listingId: ListingId;
    createdAt: Timestamp;
    stripeTransferId?: string;
    updatedAt: Timestamp;
    platformFeeUsd: number;
    buyerId: UserId;
    amountUsd: number;
    sellerId: UserId;
    sellerAmountUsd: number;
    cryptoTxnHash?: string;
    cryptoCurrency?: string;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n27(_uploadFile, _downloadFile, value.status),
        cryptoAddress: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.cryptoAddress)),
        nowPaymentsPaymentId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.nowPaymentsPaymentId)),
        listingId: value.listingId,
        createdAt: value.createdAt,
        stripeTransferId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.stripeTransferId)),
        updatedAt: value.updatedAt,
        platformFeeUsd: value.platformFeeUsd,
        buyerId: value.buyerId,
        amountUsd: value.amountUsd,
        sellerId: value.sellerId,
        sellerAmountUsd: value.sellerAmountUsd,
        cryptoTxnHash: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.cryptoTxnHash)),
        cryptoCurrency: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.cryptoCurrency))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: null;
} | {
    other: null;
} | {
    home: null;
} | {
    books: null;
} | {
    sports: null;
} | {
    digital: null;
} | {
    services: null;
} | {
    electronics: null;
}): Category {
    return "clothing" in value ? Category.clothing : "other" in value ? Category.other : "home" in value ? Category.home : "books" in value ? Category.books : "sports" in value ? Category.sports : "digital" in value ? Category.digital : "services" in value ? Category.services : "electronics" in value ? Category.electronics : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    seller: null;
} | {
    buyer: null;
}): UserRole {
    return "both" in value ? UserRole.both : "seller" in value ? UserRole.seller : "buyer" in value ? UserRole.buyer : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "paid" in value ? TransactionStatus.paid : "refunded" in value ? TransactionStatus.refunded : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ListingFilter_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilter): _ListingFilter {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ListingInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingInput): _ListingInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilter | null): [] | [_ListingFilter] {
    return value === null ? candid_none() : candid_some(to_candid_ListingFilter_n4(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coverImageUrl: string;
    title: string;
    description: string;
    category: Category;
    priceUsd: number;
}): {
    coverImageUrl: string;
    title: string;
    description: string;
    category: _Category;
    priceUsd: number;
} {
    return {
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        description: value.description,
        category: to_candid_Category_n6(_uploadFile, _downloadFile, value.category),
        priceUsd: value.priceUsd
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minPriceUsd?: number;
    maxPriceUsd?: number;
    category?: Category;
    searchQuery?: string;
}): {
    minPriceUsd: [] | [number];
    maxPriceUsd: [] | [number];
    category: [] | [_Category];
    searchQuery: [] | [string];
} {
    return {
        minPriceUsd: value.minPriceUsd ? candid_some(value.minPriceUsd) : candid_none(),
        maxPriceUsd: value.maxPriceUsd ? candid_some(value.maxPriceUsd) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n6(_uploadFile, _downloadFile, value.category)) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    both: null;
} | {
    seller: null;
} | {
    buyer: null;
} {
    return value == UserRole.both ? {
        both: null
    } : value == UserRole.seller ? {
        seller: null
    } : value == UserRole.buyer ? {
        buyer: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    clothing: null;
} | {
    other: null;
} | {
    home: null;
} | {
    books: null;
} | {
    sports: null;
} | {
    digital: null;
} | {
    services: null;
} | {
    electronics: null;
} {
    return value == Category.clothing ? {
        clothing: null
    } : value == Category.other ? {
        other: null
    } : value == Category.home ? {
        home: null
    } : value == Category.books ? {
        books: null
    } : value == Category.sports ? {
        sports: null
    } : value == Category.digital ? {
        digital: null
    } : value == Category.services ? {
        services: null
    } : value == Category.electronics ? {
        electronics: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
